# Generated by Django 3.2.6 on 2021-09-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quickpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpanel',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
    ]
