# Generated by Django 3.2.6 on 2021-09-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_quickpanel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickpanel',
            name='category',
        ),
        migrations.AddField(
            model_name='quickpanel',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shtrix_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
