# Generated by Django 3.2.6 on 2021-09-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210914_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='shtrix_code',
        ),
    ]
