# Generated by Django 3.2.6 on 2021-09-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sale_shtrix_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickPanel',
        ),
    ]
